#!/usr/bin/env bash
if [ -f $HOME/.XCompose ]; then
	cat <<'EOF' >&2
You already have a `~/.XCompose`. ext-compose will be merged
with your exististing sequences.

EOF

read -p "Merge you ~/.XCompose? [Y/n] " answer
# exit if response doesnt start with a "y" or if its empty
case $answer in 
	[!yY]*) exit ;; 
esac
fi

include=$(cat <<END
# ext-compose extensions
include "%L"
include "$PWD/base.compose"
include "$PWD/fancyletters.compose"
include "$PWD/emoji.compose"
include "$PWD/modletters.compose"
include "$PWD/japanese.compose"
include "$PWD/hangul.compose"
include "$PWD/hebrew.compose"
include "$PWD/diacritics.compose"

# add your own custom sequences below
# or rather give back and let all ext-compose
# users enjoy these sequences

END
)

cat <(echo "$include") $HOME/.XCompose | sponge $HOME/.XCompose

echo "done!"
